name: Build DLL on Windows

on:
  push:
    tags:           # ONLY run on version tag pushes like "v1.0.0"
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure
      run: cmake -S . -B build -DCMAKE_GENERATOR_PLATFORM=x64

    - name: Build
      run: cmake --build build --config Release

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/Release/*.dll
          build/Release/*.lib
          build/Release/*.pdb  # (optional debug symbols)
